import { logoMarquee } from '$utils/logo-marquee';
import { navbar } from '$utils/navbar';
import { prestingAcc } from '$utils/presting-acc';
import { senja } from '$utils/senja';
import { speakers1 } from '$utils/speakers-1';
navbar();
senja();
logoMarquee();
prestingAcc();
speakers1();
